name: 'postchangelog'
description: 'posts a changelog :/'
inputs:
  prUrl:
    description: 'pr url'
    required: true
  repoOwner:
    required: true
  repoName:
    required: true
  githubToken:
    required: true
runs:
  using: 'node12'
  main: 'index.js'
