name: 'postchangelog'
description: 'posts a changelog'
inputs:
  discordPublishWebhook:
    required: true
  discordPreviewWebhook:
    required: true
  authorisedUsers:
    description: 'Authorised users, seperated by comma'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
